### ISSUE TITLE
0.76.3 initialising a new project using React-Native-CLI doesn't work. (Windows/Android)

### ISSUE THREAD

**Issue by 3SCadmin** [react-native-community/discussions-and-proposals#834] opened 2024-11-26 15:09 UTC
Proposal:
Make it possible to submit something like this as a bug.
To submit an official bug report, you have to provide a "Reproducer" link.   That makes sense for specific coding issues... but what about general plumbing issues?   In this case the default project crashes right out of the box.   By the time I worked my way down the "bug report" to the reproducer requirement ... all I could do was swear at my monitor.

For what it's worth, here is the issue.  Please fix this.

(Windows/Android)
Following the steps in the docs [https://reactnative.dev/docs/getting-started-without-a-framework](https://reactnative.dev/docs/getting-started-without-a-framework)  (0.76.3) results in this error:

`FAILURE: Build failed with an exception.`
` * Where:
Settings file 'C:\Users\admin\coding\RN_learning\ThisWillCrash\AwesomeProject\android\settings.gradle' line: 2`
` * What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']> java.io.UncheckedIOException: Could not move temporary workspace (C:\Users\admin\coding\RN_learning\ThisWillCrash\AwesomeProject\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10-3a2c5915-b0b3-4911-a5c4-1309dbd350d6) to immutable location (C:\Users\admin\coding\RN_learning\ThisWillCrash\AwesomeProject\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10)`

After several attempts, the solution that worked for me was :  
`cd android`
`./gradlew clean`

Simple fix ...AFTER you figured it out.
Still, I think it's a big deal when step #1 sends you down a rabbit hole.   If this had been my first experience with React Native, I probably would not have bothered trying to make it work.

**Comment by cortinico** [comment] 2024-11-29 12:17
Duplicate of https://github.com/facebook/react-native/issues/46210

**Closed by cortinico** 2024-11-29 12:17 UTC
